services:
  app:
    build: ./app                    
    image: ml-service-app:latest
    container_name: ml-service-app
    restart: "no"
    env_file:
      - ./app/.env                  
    volumes:
      - ./app:/app                  
    environment:
      - PYTHONPATH=/app             
    networks:
      - ml-service-network
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ml-service-rabbitmq
    restart: on-failure
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    networks:
      - ml-service-network

  postgres:
    image: postgres:16-alpine
    container_name: ml-service-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ml_service_db
      POSTGRES_USER: ml_service_user
      POSTGRES_PASSWORD: ml_service_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - ml-service-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ml_service_user -d ml_service_db"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  ml-service-network:
    name: ml-service-network
    driver: bridge

volumes:                                    
  postgres_volume:
  rabbitmq_volume: